// Code generated by cmd/cgo; DO NOT EDIT.

package internal

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
//go:linkname _Cgo_no_callback runtime.cgoNoCallback
func _Cgo_no_callback(bool)
type _Ctype__GoString_ string

type _Ctype_char int8

type _Ctype_double float64

type _Ctype_float float32

type _Ctype_int int32

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_lua_CFunction *[0]byte

type _Ctype_lua_Continuation *[0]byte

type _Ctype_lua_Integer = _Ctype_int

type _Ctype_lua_Number = _Ctype_double

type _Ctype_lua_State = _Ctype_struct_lua_State

type _Ctype_lua_Unsigned = _Ctype_uint

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_size_t = _Ctype_ulong

type _Ctype_struct_lua_State _cgopackage.Incomplete

type _Ctype_uint uint32

type _Ctype_ulong uint64

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
//go:noescape
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
//go:noescape
func _cgoCheckResult(interface{})


// CString converts the Go string s to a C string.
//
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func _Cfunc_CString(s string) *_Ctype_char {
	if len(s)+1 <= 0 {
		panic("string too large")
	}
	p := _cgo_cmalloc(uint64(len(s)+1))
	sliceHeader := struct {
		p   unsafe.Pointer
		len int
		cap int
	}{p, len(s)+1, len(s)+1}
	b := *(*[]byte)(unsafe.Pointer(&sliceHeader))
	copy(b, s)
	b[len(s)] = 0
	return (*_Ctype_char)(p)
}

//go:linkname _cgo_runtime_gostring runtime.gostring
func _cgo_runtime_gostring(*_Ctype_char) string

// GoString converts the C string p into a Go string.
func _Cfunc_GoString(p *_Ctype_char) string {
	return _cgo_runtime_gostring(p)
}
//go:cgo_import_static _cgo_4543809e40d5_Cmacro_NULL
//go:linkname __cgofn__cgo_4543809e40d5_Cmacro_NULL _cgo_4543809e40d5_Cmacro_NULL
var __cgofn__cgo_4543809e40d5_Cmacro_NULL byte
var _cgo_4543809e40d5_Cmacro_NULL = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cmacro_NULL)

//go:cgo_unsafe_args
func _Cmacro_NULL() (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cmacro_NULL, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_clua_newstate
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_clua_newstate _cgo_4543809e40d5_Cfunc_clua_newstate
var __cgofn__cgo_4543809e40d5_Cfunc_clua_newstate byte
var _cgo_4543809e40d5_Cfunc_clua_newstate = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_clua_newstate)

//go:cgo_unsafe_args
func _Cfunc_clua_newstate(p0 unsafe.Pointer) (r1 *_Ctype_struct_lua_State) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_clua_newstate, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_free
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_free _cgo_4543809e40d5_Cfunc_free
var __cgofn__cgo_4543809e40d5_Cfunc_free byte
var _cgo_4543809e40d5_Cfunc_free = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_free)

//go:cgo_unsafe_args
func _Cfunc_free(p0 unsafe.Pointer) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_free, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_absindex
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_absindex _cgo_4543809e40d5_Cfunc_lua_absindex
var __cgofn__cgo_4543809e40d5_Cfunc_lua_absindex byte
var _cgo_4543809e40d5_Cfunc_lua_absindex = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_absindex)

//go:cgo_unsafe_args
func _Cfunc_lua_absindex(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_absindex, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_checkstack
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_checkstack _cgo_4543809e40d5_Cfunc_lua_checkstack
var __cgofn__cgo_4543809e40d5_Cfunc_lua_checkstack byte
var _cgo_4543809e40d5_Cfunc_lua_checkstack = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_checkstack)

//go:cgo_unsafe_args
func _Cfunc_lua_checkstack(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_checkstack, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_close
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_close _cgo_4543809e40d5_Cfunc_lua_close
var __cgofn__cgo_4543809e40d5_Cfunc_lua_close byte
var _cgo_4543809e40d5_Cfunc_lua_close = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_close)

//go:cgo_unsafe_args
func _Cfunc_lua_close(p0 *_Ctype_struct_lua_State) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_close, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_equal
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_equal _cgo_4543809e40d5_Cfunc_lua_equal
var __cgofn__cgo_4543809e40d5_Cfunc_lua_equal byte
var _cgo_4543809e40d5_Cfunc_lua_equal = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_equal)

//go:cgo_unsafe_args
func _Cfunc_lua_equal(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_equal, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_gettop
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_gettop _cgo_4543809e40d5_Cfunc_lua_gettop
var __cgofn__cgo_4543809e40d5_Cfunc_lua_gettop byte
var _cgo_4543809e40d5_Cfunc_lua_gettop = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_gettop)

//go:cgo_unsafe_args
func _Cfunc_lua_gettop(p0 *_Ctype_struct_lua_State) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_gettop, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_insert
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_insert _cgo_4543809e40d5_Cfunc_lua_insert
var __cgofn__cgo_4543809e40d5_Cfunc_lua_insert byte
var _cgo_4543809e40d5_Cfunc_lua_insert = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_insert)

//go:cgo_unsafe_args
func _Cfunc_lua_insert(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_insert, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_isLfunction
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_isLfunction _cgo_4543809e40d5_Cfunc_lua_isLfunction
var __cgofn__cgo_4543809e40d5_Cfunc_lua_isLfunction byte
var _cgo_4543809e40d5_Cfunc_lua_isLfunction = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_isLfunction)

//go:cgo_unsafe_args
func _Cfunc_lua_isLfunction(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_isLfunction, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_iscfunction
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_iscfunction _cgo_4543809e40d5_Cfunc_lua_iscfunction
var __cgofn__cgo_4543809e40d5_Cfunc_lua_iscfunction byte
var _cgo_4543809e40d5_Cfunc_lua_iscfunction = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_iscfunction)

//go:cgo_unsafe_args
func _Cfunc_lua_iscfunction(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_iscfunction, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_isnumber
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_isnumber _cgo_4543809e40d5_Cfunc_lua_isnumber
var __cgofn__cgo_4543809e40d5_Cfunc_lua_isnumber byte
var _cgo_4543809e40d5_Cfunc_lua_isnumber = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_isnumber)

//go:cgo_unsafe_args
func _Cfunc_lua_isnumber(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_isnumber, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_isstring
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_isstring _cgo_4543809e40d5_Cfunc_lua_isstring
var __cgofn__cgo_4543809e40d5_Cfunc_lua_isstring byte
var _cgo_4543809e40d5_Cfunc_lua_isstring = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_isstring)

//go:cgo_unsafe_args
func _Cfunc_lua_isstring(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_isstring, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_isthreadreset
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_isthreadreset _cgo_4543809e40d5_Cfunc_lua_isthreadreset
var __cgofn__cgo_4543809e40d5_Cfunc_lua_isthreadreset byte
var _cgo_4543809e40d5_Cfunc_lua_isthreadreset = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_isthreadreset)

//go:cgo_unsafe_args
func _Cfunc_lua_isthreadreset(p0 *_Ctype_struct_lua_State) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_isthreadreset, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_isuserdata
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_isuserdata _cgo_4543809e40d5_Cfunc_lua_isuserdata
var __cgofn__cgo_4543809e40d5_Cfunc_lua_isuserdata byte
var _cgo_4543809e40d5_Cfunc_lua_isuserdata = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_isuserdata)

//go:cgo_unsafe_args
func _Cfunc_lua_isuserdata(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_isuserdata, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_lessthan
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_lessthan _cgo_4543809e40d5_Cfunc_lua_lessthan
var __cgofn__cgo_4543809e40d5_Cfunc_lua_lessthan byte
var _cgo_4543809e40d5_Cfunc_lua_lessthan = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_lessthan)

//go:cgo_unsafe_args
func _Cfunc_lua_lessthan(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_lessthan, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_lightuserdatatag
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_lightuserdatatag _cgo_4543809e40d5_Cfunc_lua_lightuserdatatag
var __cgofn__cgo_4543809e40d5_Cfunc_lua_lightuserdatatag byte
var _cgo_4543809e40d5_Cfunc_lua_lightuserdatatag = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_lightuserdatatag)

//go:cgo_unsafe_args
func _Cfunc_lua_lightuserdatatag(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_lightuserdatatag, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_mainthread
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_mainthread _cgo_4543809e40d5_Cfunc_lua_mainthread
var __cgofn__cgo_4543809e40d5_Cfunc_lua_mainthread byte
var _cgo_4543809e40d5_Cfunc_lua_mainthread = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_mainthread)

//go:cgo_unsafe_args
func _Cfunc_lua_mainthread(p0 *_Ctype_struct_lua_State) (r1 *_Ctype_struct_lua_State) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_mainthread, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_namecallatom
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_namecallatom _cgo_4543809e40d5_Cfunc_lua_namecallatom
var __cgofn__cgo_4543809e40d5_Cfunc_lua_namecallatom byte
var _cgo_4543809e40d5_Cfunc_lua_namecallatom = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_namecallatom)

//go:cgo_unsafe_args
func _Cfunc_lua_namecallatom(p0 *_Ctype_struct_lua_State, p1 *_Ctype_int) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_namecallatom, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_newthread
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_newthread _cgo_4543809e40d5_Cfunc_lua_newthread
var __cgofn__cgo_4543809e40d5_Cfunc_lua_newthread byte
var _cgo_4543809e40d5_Cfunc_lua_newthread = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_newthread)

//go:cgo_unsafe_args
func _Cfunc_lua_newthread(p0 *_Ctype_struct_lua_State) (r1 *_Ctype_struct_lua_State) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_newthread, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_objlen
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_objlen _cgo_4543809e40d5_Cfunc_lua_objlen
var __cgofn__cgo_4543809e40d5_Cfunc_lua_objlen byte
var _cgo_4543809e40d5_Cfunc_lua_objlen = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_objlen)

//go:cgo_unsafe_args
func _Cfunc_lua_objlen(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_objlen, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushcclosurek
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushcclosurek _cgo_4543809e40d5_Cfunc_lua_pushcclosurek
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushcclosurek byte
var _cgo_4543809e40d5_Cfunc_lua_pushcclosurek = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushcclosurek)

//go:cgo_unsafe_args
func _Cfunc_lua_pushcclosurek(p0 *_Ctype_struct_lua_State, p1 *[0]byte, p2 *_Ctype_char, p3 _Ctype_int, p4 *[0]byte) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushcclosurek, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushinteger
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushinteger _cgo_4543809e40d5_Cfunc_lua_pushinteger
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushinteger byte
var _cgo_4543809e40d5_Cfunc_lua_pushinteger = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushinteger)

//go:cgo_unsafe_args
func _Cfunc_lua_pushinteger(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushinteger, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushlstring
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushlstring _cgo_4543809e40d5_Cfunc_lua_pushlstring
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushlstring byte
var _cgo_4543809e40d5_Cfunc_lua_pushlstring = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushlstring)

//go:cgo_unsafe_args
func _Cfunc_lua_pushlstring(p0 *_Ctype_struct_lua_State, p1 *_Ctype_char, p2 _Ctype_size_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushlstring, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushnil
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushnil _cgo_4543809e40d5_Cfunc_lua_pushnil
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushnil byte
var _cgo_4543809e40d5_Cfunc_lua_pushnil = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushnil)

//go:cgo_unsafe_args
func _Cfunc_lua_pushnil(p0 *_Ctype_struct_lua_State) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushnil, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushnumber
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushnumber _cgo_4543809e40d5_Cfunc_lua_pushnumber
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushnumber byte
var _cgo_4543809e40d5_Cfunc_lua_pushnumber = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushnumber)

//go:cgo_unsafe_args
func _Cfunc_lua_pushnumber(p0 *_Ctype_struct_lua_State, p1 _Ctype_double) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushnumber, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushstring
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushstring _cgo_4543809e40d5_Cfunc_lua_pushstring
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushstring byte
var _cgo_4543809e40d5_Cfunc_lua_pushstring = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushstring)

//go:cgo_unsafe_args
func _Cfunc_lua_pushstring(p0 *_Ctype_struct_lua_State, p1 *_Ctype_char) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushstring, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushunsigned
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushunsigned _cgo_4543809e40d5_Cfunc_lua_pushunsigned
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushunsigned byte
var _cgo_4543809e40d5_Cfunc_lua_pushunsigned = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushunsigned)

//go:cgo_unsafe_args
func _Cfunc_lua_pushunsigned(p0 *_Ctype_struct_lua_State, p1 _Ctype_uint) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushunsigned, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_pushvalue
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_pushvalue _cgo_4543809e40d5_Cfunc_lua_pushvalue
var __cgofn__cgo_4543809e40d5_Cfunc_lua_pushvalue byte
var _cgo_4543809e40d5_Cfunc_lua_pushvalue = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_pushvalue)

//go:cgo_unsafe_args
func _Cfunc_lua_pushvalue(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_pushvalue, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_rawcheckstack
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_rawcheckstack _cgo_4543809e40d5_Cfunc_lua_rawcheckstack
var __cgofn__cgo_4543809e40d5_Cfunc_lua_rawcheckstack byte
var _cgo_4543809e40d5_Cfunc_lua_rawcheckstack = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_rawcheckstack)

//go:cgo_unsafe_args
func _Cfunc_lua_rawcheckstack(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_rawcheckstack, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_rawequal
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_rawequal _cgo_4543809e40d5_Cfunc_lua_rawequal
var __cgofn__cgo_4543809e40d5_Cfunc_lua_rawequal byte
var _cgo_4543809e40d5_Cfunc_lua_rawequal = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_rawequal)

//go:cgo_unsafe_args
func _Cfunc_lua_rawequal(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_rawequal, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_remove
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_remove _cgo_4543809e40d5_Cfunc_lua_remove
var __cgofn__cgo_4543809e40d5_Cfunc_lua_remove byte
var _cgo_4543809e40d5_Cfunc_lua_remove = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_remove)

//go:cgo_unsafe_args
func _Cfunc_lua_remove(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_remove, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_replace
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_replace _cgo_4543809e40d5_Cfunc_lua_replace
var __cgofn__cgo_4543809e40d5_Cfunc_lua_replace byte
var _cgo_4543809e40d5_Cfunc_lua_replace = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_replace)

//go:cgo_unsafe_args
func _Cfunc_lua_replace(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_replace, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_resetthread
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_resetthread _cgo_4543809e40d5_Cfunc_lua_resetthread
var __cgofn__cgo_4543809e40d5_Cfunc_lua_resetthread byte
var _cgo_4543809e40d5_Cfunc_lua_resetthread = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_resetthread)

//go:cgo_unsafe_args
func _Cfunc_lua_resetthread(p0 *_Ctype_struct_lua_State) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_resetthread, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_settop
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_settop _cgo_4543809e40d5_Cfunc_lua_settop
var __cgofn__cgo_4543809e40d5_Cfunc_lua_settop byte
var _cgo_4543809e40d5_Cfunc_lua_settop = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_settop)

//go:cgo_unsafe_args
func _Cfunc_lua_settop(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_settop, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_toboolean
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_toboolean _cgo_4543809e40d5_Cfunc_lua_toboolean
var __cgofn__cgo_4543809e40d5_Cfunc_lua_toboolean byte
var _cgo_4543809e40d5_Cfunc_lua_toboolean = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_toboolean)

//go:cgo_unsafe_args
func _Cfunc_lua_toboolean(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_toboolean, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tobuffer
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tobuffer _cgo_4543809e40d5_Cfunc_lua_tobuffer
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tobuffer byte
var _cgo_4543809e40d5_Cfunc_lua_tobuffer = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tobuffer)

//go:cgo_unsafe_args
func _Cfunc_lua_tobuffer(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 *_Ctype_size_t) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tobuffer, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tocfunction
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tocfunction _cgo_4543809e40d5_Cfunc_lua_tocfunction
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tocfunction byte
var _cgo_4543809e40d5_Cfunc_lua_tocfunction = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tocfunction)

//go:cgo_unsafe_args
func _Cfunc_lua_tocfunction(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_lua_CFunction) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tocfunction, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tointegerx
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tointegerx _cgo_4543809e40d5_Cfunc_lua_tointegerx
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tointegerx byte
var _cgo_4543809e40d5_Cfunc_lua_tointegerx = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tointegerx)

//go:cgo_unsafe_args
func _Cfunc_lua_tointegerx(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 *_Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tointegerx, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tolightuserdata
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tolightuserdata _cgo_4543809e40d5_Cfunc_lua_tolightuserdata
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tolightuserdata byte
var _cgo_4543809e40d5_Cfunc_lua_tolightuserdata = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tolightuserdata)

//go:cgo_unsafe_args
func _Cfunc_lua_tolightuserdata(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tolightuserdata, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tolightuserdatatagged
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tolightuserdatatagged _cgo_4543809e40d5_Cfunc_lua_tolightuserdatatagged
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tolightuserdatatagged byte
var _cgo_4543809e40d5_Cfunc_lua_tolightuserdatatagged = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tolightuserdatatagged)

//go:cgo_unsafe_args
func _Cfunc_lua_tolightuserdatatagged(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 _Ctype_int) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tolightuserdatatagged, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tolstring
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tolstring _cgo_4543809e40d5_Cfunc_lua_tolstring
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tolstring byte
var _cgo_4543809e40d5_Cfunc_lua_tolstring = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tolstring)

//go:cgo_unsafe_args
func _Cfunc_lua_tolstring(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 *_Ctype_size_t) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tolstring, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tonumberx
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tonumberx _cgo_4543809e40d5_Cfunc_lua_tonumberx
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tonumberx byte
var _cgo_4543809e40d5_Cfunc_lua_tonumberx = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tonumberx)

//go:cgo_unsafe_args
func _Cfunc_lua_tonumberx(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 *_Ctype_int) (r1 _Ctype_double) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tonumberx, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_topointer
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_topointer _cgo_4543809e40d5_Cfunc_lua_topointer
var __cgofn__cgo_4543809e40d5_Cfunc_lua_topointer byte
var _cgo_4543809e40d5_Cfunc_lua_topointer = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_topointer)

//go:cgo_unsafe_args
func _Cfunc_lua_topointer(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_topointer, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tostringatom
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tostringatom _cgo_4543809e40d5_Cfunc_lua_tostringatom
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tostringatom byte
var _cgo_4543809e40d5_Cfunc_lua_tostringatom = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tostringatom)

//go:cgo_unsafe_args
func _Cfunc_lua_tostringatom(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 *_Ctype_int) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tostringatom, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tothread
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tothread _cgo_4543809e40d5_Cfunc_lua_tothread
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tothread byte
var _cgo_4543809e40d5_Cfunc_lua_tothread = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tothread)

//go:cgo_unsafe_args
func _Cfunc_lua_tothread(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 *_Ctype_struct_lua_State) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tothread, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tounsignedx
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tounsignedx _cgo_4543809e40d5_Cfunc_lua_tounsignedx
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tounsignedx byte
var _cgo_4543809e40d5_Cfunc_lua_tounsignedx = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tounsignedx)

//go:cgo_unsafe_args
func _Cfunc_lua_tounsignedx(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 *_Ctype_int) (r1 _Ctype_uint) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tounsignedx, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_touserdata
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_touserdata _cgo_4543809e40d5_Cfunc_lua_touserdata
var __cgofn__cgo_4543809e40d5_Cfunc_lua_touserdata byte
var _cgo_4543809e40d5_Cfunc_lua_touserdata = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_touserdata)

//go:cgo_unsafe_args
func _Cfunc_lua_touserdata(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_touserdata, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_touserdatatagged
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_touserdatatagged _cgo_4543809e40d5_Cfunc_lua_touserdatatagged
var __cgofn__cgo_4543809e40d5_Cfunc_lua_touserdatatagged byte
var _cgo_4543809e40d5_Cfunc_lua_touserdatatagged = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_touserdatatagged)

//go:cgo_unsafe_args
func _Cfunc_lua_touserdatatagged(p0 *_Ctype_struct_lua_State, p1 _Ctype_int, p2 _Ctype_int) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_touserdatatagged, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_tovector
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_tovector _cgo_4543809e40d5_Cfunc_lua_tovector
var __cgofn__cgo_4543809e40d5_Cfunc_lua_tovector byte
var _cgo_4543809e40d5_Cfunc_lua_tovector = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_tovector)

//go:cgo_unsafe_args
func _Cfunc_lua_tovector(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 *_Ctype_float) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_tovector, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_type
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_type _cgo_4543809e40d5_Cfunc_lua_type
var __cgofn__cgo_4543809e40d5_Cfunc_lua_type byte
var _cgo_4543809e40d5_Cfunc_lua_type = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_type)

//go:cgo_unsafe_args
func _Cfunc_lua_type(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_type, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_typename
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_typename _cgo_4543809e40d5_Cfunc_lua_typename
var __cgofn__cgo_4543809e40d5_Cfunc_lua_typename byte
var _cgo_4543809e40d5_Cfunc_lua_typename = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_typename)

//go:cgo_unsafe_args
func _Cfunc_lua_typename(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_typename, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_userdatatag
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_userdatatag _cgo_4543809e40d5_Cfunc_lua_userdatatag
var __cgofn__cgo_4543809e40d5_Cfunc_lua_userdatatag byte
var _cgo_4543809e40d5_Cfunc_lua_userdatatag = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_userdatatag)

//go:cgo_unsafe_args
func _Cfunc_lua_userdatatag(p0 *_Ctype_struct_lua_State, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_userdatatag, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_xmove
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_xmove _cgo_4543809e40d5_Cfunc_lua_xmove
var __cgofn__cgo_4543809e40d5_Cfunc_lua_xmove byte
var _cgo_4543809e40d5_Cfunc_lua_xmove = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_xmove)

//go:cgo_unsafe_args
func _Cfunc_lua_xmove(p0 *_Ctype_struct_lua_State, p1 *_Ctype_struct_lua_State, p2 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_xmove, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_4543809e40d5_Cfunc_lua_xpush
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc_lua_xpush _cgo_4543809e40d5_Cfunc_lua_xpush
var __cgofn__cgo_4543809e40d5_Cfunc_lua_xpush byte
var _cgo_4543809e40d5_Cfunc_lua_xpush = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc_lua_xpush)

//go:cgo_unsafe_args
func _Cfunc_lua_xpush(p0 *_Ctype_struct_lua_State, p1 *_Ctype_struct_lua_State, p2 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc_lua_xpush, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_export_dynamic go_allocf
//go:linkname _cgoexp_4543809e40d5_go_allocf _cgoexp_4543809e40d5_go_allocf
//go:cgo_export_static _cgoexp_4543809e40d5_go_allocf
func _cgoexp_4543809e40d5_go_allocf(a *struct {
		p0 uintptr
		p1 uintptr
		p2 uint64
		p3 uint64
		r0 uintptr
	}) {
	a.r0 = go_allocf(a.p0, a.p1, a.p2, a.p3)
	_cgoCheckResult(a.r0)
}

//go:cgo_import_static _cgo_4543809e40d5_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_4543809e40d5_Cfunc__Cmalloc _cgo_4543809e40d5_Cfunc__Cmalloc
var __cgofn__cgo_4543809e40d5_Cfunc__Cmalloc byte
var _cgo_4543809e40d5_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_4543809e40d5_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_4543809e40d5_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
